---
apiVersion: v1
kind: Service
metadata:
  name: matomo 
  namespace: web-analytics
spec:
  type: LoadBalancer
  selector:
    app: matomo
    tier: web
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: matomo
  namespace: web-analytics
  labels:
    app: matomo
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
      tier: web
  template:
    metadata:
      labels:
        app: matomo
        tier: web
    spec:
      containers:
        - name: matomo
          image: notemaker/matomo:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html"
              name: matomo-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE 
              value: matomo
            - name: MYSQL_USER
              value: matomo 
            - name: MATOMO_DATABASE_HOST
              value: mysql
            - name: MATOMO_DATABASE_ADAPTER
              value: mysql 
            - name: MATOMO_DATABASE_TABLES_PREFIX
              value: matomo_
            - name: MATOMO_DATABASE_USERNAME
              value: matomo
      volumes:
        - name: matomo-data
          persistentVolumeClaim:
            claimName: matomo-pvc 

